### ISSUE TITLE
This is cool but how do you add name-spacing to html classes?

### ISSUE THREAD

**Issue by jitendravyas** [GarthDB/postcss-add-namespace#46]

**Comment by GarthDB** [comment]
In the HTML? Depends on how you're doing your HTML.

**Comment by remorses** [comment]
My use case is that I am using tailwind css to style some components for a npm library, i will bundle the compiled tailwind css  in the npm package, the problem is that if the consumer is using tailwind he will have confilcts and duplicate classes, 

i thought this plugin could add the namespace to the css and the html classes too (maybe webpack loader?), so that i don't have to repeat the prefix in my code 1000 times.

do you know a way to do it?

**Comment by remorses** [comment]
i found this https://github.com/vaheqelyan/react-classnamePrefix-loader
